### ISSUE TITLE
AMP-binding links to wrong Pfam domain

### ISSUE THREAD

**Issue by hyphaltip** [antismash/documentation#5]
https://github.com/antismash/documentation/blob/61a185741926632894b0ef8a4cf4b53b4c0386ea/docs/modules/nrps_pks_domains.md?plain=1#L16
this table links to https://www.ebi.ac.uk/interpro/entry/pfam/PF00502/ for AMP-Binding but the correct domain ID is PF00501 and should be corrected to https://www.ebi.ac.uk/interpro/entry/pfam/PF00501/

**Comment by SJShaw** [comment]
Fixed in 79c3818
