### ISSUE TITLE
Docker install points to not existing page

### ISSUE THREAD

**Issue by FriederikeBiermann** [antismash/documentation#8]
I noticed that the download links for the antiSMASH wrappers are no longer active, and I've been unable to locate alternative sources. It would be beneficial to either update these links or remove this section from the documentation for clarity. Additionally, it's worth mentioning that the bioconda installation method has been ineffective since version 7, highlighting the need for this update.

antiSMASH standalone[#](https://docs.antismash.secondarymetabolites.org/install/#antismash-standalone)

This image includes all the required databases, no further configuration needed. It is a ~9 GB download at the moment. If you have docker installed, just grab the wrapper script and get going:

mkdir ~/bin    # not required if you already have that
curl -q https://dl.secondarymetabolites.org/releases/latest/docker-run_antismash-full > ~/bin/run_antismash
chmod a+x ~/bin/run_antismash
run_antismash <input file> <output directory> [antismash options]

Note that due to the nature of the wrapper script having to do some magic mapping between your system and the container, you always need to provide input file and output directory first, and in that order.
antiSMASH standalone-lite[#](https://docs.antismash.secondarymetabolites.org/install/#antismash-standalone-lite)

This image includes everything but the PFAM and ClusterBlast databases, meaning you still have to install those. The wrapper script assumes those databases will live in /data/databases, make sure to tweak the script and the rest of the install instructions if you want to change this location.

First, grab the wrapper script:

mkdir ~/bin    # not required if you already have that
curl -q https://dl.secondarymetabolites.org/releases/latest/docker-run_antismash-lite > ~/bin/run_antismash
chmod a+x ~/bin/run_antismash

The easiest way to download the antiSMASH databases is using the database downloader script. Again the wrapper script assumes your databases live in /data/databases. If you want to use a different location, just provide that to the download_antismash_databases script as the parameter.

curl -q https://dl.secondarymetabolites.org/releases/latest/download_antismash_databases > ~/bin/download_antismash_databases
chmod a+x ~/bin/download_antismash_databases
download_antismash_databases

Note that due to the nature of the wrapper script having to do some magic mapping between your system and the container, you always need to provide input file and output directory first, and in that order:

run_antismash <input file> <output directory> [antismash options]

**Comment by kblin** [comment]
A slight hiccup in our release process forced us to tag a 7.1.0.1 release to fix some package versions in the pinned dependencies, and that in turn broke a release script that updates the `latest/` symlink. This is fixed now, all the links in the documentation should now work again.

Additionally, the database download script was updated to reflect the fact that we now support docker and podman.

Lastly, our bioconda packages are blocked by https://github.com/bioconda/bioconda-recipes/issues/44377, not much we can do about that from our side.

**Comment by FriederikeBiermann** [comment]
Thank you!!
